set(PLATFORM "x86_64-linux-gnu")

if(NOT CMAKE_HOST_LINUX OR NOT CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "(x86_64|AMD64)")
    find_program(CMAKE_CROSSCOMPILING_EMULATOR NAMES qemu-x86_64 REQUIRED)

    set(CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_SYSTEM_PROCESSOR x86_64)

    set(CMAKE_CROSSCOMPILING ON)

    if(DEFINED ENV{SYSROOT_PREFIX})
        set(CMAKE_SYSROOT "$ENV{SYSROOT_PREFIX}/${PLATFORM}")
    else()
        if(CMAKE_HOST_WIN32)
            set(CMAKE_SYSROOT "C:\\Toolchain\\${PLATFORM}")
        elseif(CMAKE_HOST_LINUX)
            set(CMAKE_SYSROOT "/usr/${PLATFORM}")
        elseif(CMAKE_HOST_UNIX)
            set(CMAKE_SYSROOT "/opt/${PLATFORM}")
        endif()
    endif()

    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
