include(${CMAKE_CURRENT_LIST_DIR}/Default.cmake)

if(NOT CMAKE_HOST_LINUX OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "(x86_64|AMD64)")
    find_program(CMAKE_C_COMPILER NAMES ${PLATFORM}-gcc REQUIRED)
    find_program(CMAKE_CXX_COMPILER NAMES ${PLATFORM}-g++ REQUIRED)
    find_program(CMAKE_AR NAMES ${PLATFORM}-gcc-ar REQUIRED)
    find_program(CMAKE_RANLIB NAMES ${PLATFORM}-gcc-ranlib REQUIRED)
    find_program(CMAKE_NM NAMES ${PLATFORM}-gcc-nm REQUIRED)

    if(CMAKE_HOST_UNIX)
        find_program(CMAKE_LINKER NAMES mold ${PLATFORM}-ld REQUIRED)
    else()
        find_program(CMAKE_LINKER NAMES ${PLATFORM}-ld REQUIRED)
    endif()

    if(CMAKE_LINKER MATCHES mold)
        set(CMAKE_LINKER_TYPE MOLD)
    else()
        set(CMAKE_LINKER_TYPE BFD)
    endif()
endif()
