################################################
###### This is an embedded package manager #####
################################################
###### Please do not change anything here ######
################################################

if(CMAKE_DEPENDENCIES_SYSTEM_ADAPTER)
    message(NOTICE
        [[###############################################]] \n
        [[######## Generated by CMakeDependencies #######]] \n
        [[###############################################]] \n\n
        [[cmake_minimum_required(VERSION 3.31)]] \n\n
        [[if(NOT @CMAKE_HOST_TARGET@)]] \n
        \t [[message(AUTHOR_WARNING]] \n
        \t\t [["This package was built for @CMAKE_TARGET_SYSTEM_NAME@." \n]] \n
        \t\t [["It may not work properly on ${CMAKE_HOST_SYSTEM_NAME}"]] \n\n
        \t [[)]] \n
        [[endif()]] \n\n
        [[# The prefix will always be at <source>/.modules, which is CMAKE_DEPENDENCY_DESTINATION]] \n
        [[set(IMPORT_PREFIX "@CMAKE_DEPENDENCY_DESTINATION@")]] \n\n
        [[# Create imported targets]] \n
        [[foreach(TARGET_LOCATION IN ITEMS @DEPENDENCY_EXPORTS@)]] \n
        \t [[cmake_path(GET TARGET_LOCATION FILENAME TARGET)]] \n\n
        \t [[if("${TARGET}" MATCHES "@CMAKE_SHARED_LIBRARY_PREFIX@(.*)@CMAKE_SHARED_LIBRARY_SUFFIX@")]] \n
        \t\t [[if(TARGET "@DEPENDENCY@::${CMAKE_MATCH_1}") ]] \n
        \t\t\t [[message(FATAL_ERROR "Target '@DEPENDENCY@::${CMAKE_MATCH_1}' is already defined.")]] \n
        \t\t [[endif()]] \n\n
        \t\t [[add_library(@DEPENDENCY@::${CMAKE_MATCH_1} SHARED IMPORTED)]] \n\n
        \t\t [[set_target_properties(@DEPENDENCY@::${CMAKE_MATCH_1} PROPERTIES]] \n
        \t\t\t [[IMPORTED_LINK_INTERFACE_LANGUAGES "@DEPENDENCY_LANGUAGES@"]] \n
        \t\t\t [[IMPORTED_LOCATION "${IMPORT_PREFIX}/${TARGET_LOCATION}"]] \n
        \t\t\t [[INTERFACE_INCLUDE_DIRECTORIES "${IMPORT_PREFIX}/@CMAKE_INSTALL_INCLUDEDIR@"]] \n
        \t\t [[)]] \n
        \t [[elseif("${TARGET}" MATCHES "@CMAKE_STATIC_LIBRARY_PREFIX@(.*)@CMAKE_STATIC_LIBRARY_SUFFIX@")]] \n
        \t\t [[if(TARGET "@DEPENDENCY@::${CMAKE_MATCH_1}") ]] \n
        \t\t\t [[message(FATAL_ERROR "Target '@DEPENDENCY@::${CMAKE_MATCH_1}' is already defined.")]] \n
        \t\t [[endif()]] \n\n
        \t\t [[add_library(@DEPENDENCY@::${CMAKE_MATCH_1} STATIC IMPORTED)]] \n\n
        \t\t [[set_target_properties(@DEPENDENCY@::${CMAKE_MATCH_1} PROPERTIES]] \n
        \t\t\t [[IMPORTED_LINK_INTERFACE_LANGUAGES "@DEPENDENCY_LANGUAGES@"]] \n
        \t\t\t [[IMPORTED_LOCATION "${IMPORT_PREFIX}/${TARGET_LOCATION}"]] \n
        \t\t\t [[INTERFACE_INCLUDE_DIRECTORIES "${IMPORT_PREFIX}/@CMAKE_INSTALL_INCLUDEDIR@"]] \n
        \t\t [[)]] \n
        \t [[elseif("${TARGET}" MATCHES "(.*)@CMAKE_EXECUTABLE_SUFFIX@" AND IS_EXECUTABLE "${TARGET_LOCATION}")]] \n
        \t\t [[if(TARGET "@DEPENDENCY@::${CMAKE_MATCH_1}") ]] \n
        \t\t\t [[message(FATAL_ERROR "Target '@DEPENDENCY@::${CMAKE_MATCH_1}' is already defined.")]] \n
        \t\t [[endif()]] \n\n
        \t\t [[add_executable(@DEPENDENCY@::${CMAKE_MATCH_1} IMPORTED)]] \n\n
        \t\t [[set_target_properties(@DEPENDENCY@::${CMAKE_MATCH_1} PROPERTIES]] \n
        \t\t\t [[IMPORTED_LOCATION "${IMPORT_PREFIX}/${TARGET_LOCATION}"]] \n
        \t\t\t [[INTERFACE_INCLUDE_DIRECTORIES "${IMPORT_PREFIX}/@CMAKE_INSTALL_INCLUDEDIR@"]] \n
        \t\t [[)]] \n
        \t [[endif()]] \n\n
        \t [[if(NOT EXISTS "${IMPORT_PREFIX}/${TARGET_LOCATION}")]] \n
        \t\t [[message(FATAL_ERROR]] \n
        \t\t\t [["The imported target \"${FILE}\" references the file" \n]] \n
        \t\t\t [[\t "${FILE}" \n]] \n
        \t\t\t [["but this file does not exist. Possible reasons include:" \n]] \n
        \t\t\t [[\t "* The file was deleted, renamed, or moved to another location." \n]] \n
        \t\t\t [[\t "* An install or uninstall procedure did not complete successfully." \n]] \n
        \t\t\t [[\t "* The installation package was faulty and contained" \n]] \n
        \t\t\t [[\t\t "${CMAKE_CURRENT_LIST_FILE}" \n]] \n
        \t\t\t [[\t "but not all the files it references."]] \n
        \t\t [[)]] \n
        \t [[endif()]] \n
        [[endforeach()]] \n\n
        [[# Commands beyond this point should not need to know the version.]] \n
        [[unset(CMAKE_IMPORT_FILE_VERSION)]] \n
        [[unset(IMPORT_PREFIX)]]
    )

    return()
endif()

include(GNUInstallDirs)

set(CMAKE_DEPENDENCY_MANIFEST "${CMAKE_SOURCE_DIR}/cmake/dependencies"
    CACHE STRING "The directory which will be searched for dependency manifests"
)

set(CMAKE_DEPENDENCY_ROOT "${CMAKE_SOURCE_DIR}/.modules"
    CACHE STRING "The root directory for things such as exported artifacts, source code, etc"
)

set(CMAKE_DEPENDENCY_DESTINATION "${CMAKE_DEPENDENCY_ROOT}"
    CACHE STRING "The location that the exported artifacts of dependencies will be installed unto"
)

set(CMAKE_DEPENDENCY_SOURCE "${CMAKE_DEPENDENCY_ROOT}/src"
    CACHE STRING "The location where the source code of dependencies will be saved"
)

set(CMAKE_DEPENDENCY_STAGE "${CMAKE_BINARY_DIR}/CMakeDependencies"
    CACHE STRING "The root location that dependencies will be built on"
)

set(CMAKE_LOCKFILE "${CMAKE_DEPENDENCY_ROOT}/CMakeLockfile.cmake"
    CACHE STRING "The lockfile for CMake dependencies"
)

list(PREPEND CMAKE_PREFIX_PATH
    "${CMAKE_DEPENDENCY_DESTINATION}"
    "${CMAKE_DEPENDENCY_DESTINATION}/${CMAKE_INSTALL_LIBDIR}"
)

block()

cmake_host_system_information(RESULT NPROC QUERY NUMBER_OF_LOGICAL_CORES)

if(CMAKE_HOST_WIN32)
    set(SUPPORTED_BUILD_SYSTEMS
        CMake
        Meson
        CACHE STRING "The supported build systems for Windows"
    )
else(CMAKE_HOST_UNIX)
    set(SUPPORTED_BUILD_SYSTEMS
        CMake
        Meson
        Autoconf
        CACHE STRING "The supported build systems for Unix-like system"
    )
endif()

set(SUPPORTED_URL_TYPES
    Github
    Custom
    CACHE STRING "The supported URL types for dependency fetching"
)

if(NOT EXISTS ${CMAKE_DEPENDENCY_DESTINATION})
    file(MAKE_DIRECTORY "${CMAKE_DEPENDENCY_DESTINATION}")
endif()

if(NOT EXISTS ${CMAKE_DEPENDENCY_SOURCE})
    file(MAKE_DIRECTORY "${CMAKE_DEPENDENCY_SOURCE}")
endif()

if(NOT EXISTS ${CMAKE_DEPENDENCY_STAGE})
    file(MAKE_DIRECTORY "${CMAKE_DEPENDENCY_STAGE}")
endif()

#############################################################
##################### Logging functions #####################
#############################################################

function(status)
    cmake_parse_arguments(PARSE_ARGV 0
        "LOG"
        "ERROR;WARN;INFO"
        "MESSAGE;OUTPUT;PREFIX"
        ""
    )

    string(ASCII 27 ESC)

    if(NOT DEFINED LOG_TYPE)
        set(LOG_TYPE "INFO")
    endif()

    if($ENV{COLORTERM} MATCHES "(truecolor|24bit|24-bit)" OR CMAKE_HOST_WIN32)
        set(COLOR_SUPPORT "truecolor")
    else()
        set(COLOR_SUPPORT "standard")
    endif()

    if(COLOR_SUPPORT STREQUAL truecolor)
        set(INFO_COLOR "${ESC}[38;2;43;136;221m")
        set(WARN_COLOR "${ESC}[38;2;157;24;216m")
        set(ERROR_COLOR "${ESC}[38;2;221;43;43m")
    elseif(COLOR_SUPPORT STREQUAL standard)
        set(INFO_COLOR "${ESC}[36m")
        set(WARN_COLOR "${ESC}[35m")
        set(ERROR_COLOR "${ESC}[31m")
    endif()

    if(DEFINED LOG_PREFIX AND NOT LOG_PREFIX MATCHES " $")
        set(LOG_PREFIX "${LOG_PREFIX} ")
    endif()

    if(LOG_ERROR)
        if(DEFINED LOG_OUTPUT)
            set(${LOG_OUTPUT} "${ERROR_COLOR}${LOG_PREFIX}ERROR:${ESC}[0m ${LOG_MESSAGE}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${LOG_MESSAGE}")
        endif()
    elseif(LOG_WARN)
        if(DEFINED LOG_OUTPUT)
            set(${LOG_OUTPUT} "${WARN_COLOR}${LOG_PREFIX}WARN:${ESC}[0m ${LOG_MESSAGE}" PARENT_SCOPE)
        else()
            message(STATUS "${WARN_COLOR}${LOG_PREFIX}WARN:${ESC}[0m ${LOG_MESSAGE}")
        endif()
    elseif(LOG_INFO)
        if(DEFINED LOG_OUTPUT)
            set(${LOG_OUTPUT} "${INFO_COLOR}${LOG_PREFIX}INFO:${ESC}[0m ${LOG_MESSAGE}" PARENT_SCOPE)
        else()
            message(STATUS "${INFO_COLOR}${LOG_PREFIX}INFO:${ESC}[0m ${LOG_MESSAGE}")
        endif()
    endif()

    return()
endfunction()

#############################################################
####################### URL functions #######################
#############################################################

function(get_url_type)
    cmake_parse_arguments(PARSE_ARGV 0
        ""
        ""
        "URL;OUTPUT"
        ""
    )

    if(_URL MATCHES ^https://github.com OR _URL MATCHES ^git@github.com)
        set(${_OUTPUT} Github PARENT_SCOPE)
    else()
        set(${_OUTPUT} Custom PARENT_SCOPE)
    endif()

    return()
endfunction()

function(fetch_url)
    cmake_parse_arguments(PARSE_ARGV 0
        "FETCH"
        ""
        "URL;ID;DESTINATION"
        ""
    )

    if(NOT DEFINED FETCH_URL)
        status(ERROR MESSAGE "Must specify a URL to be fetched" PREFIX FETCH)
    endif()

    if(NOT DEFINED FETCH_ID)
        status(ERROR MESSAGE "Must specify a URL ID to be able to fetch a URL" PREFIX FETCH)
    endif()

    if(NOT DEFINED FETCH_DESTINATION)
        status(ERROR MESSAGE "Must specify a destination to place the fetched artifact" PREFIX FETCH)
    endif()

    get_url_type(URL "${FETCH_URL}" OUTPUT URL_TYPE)

    if(URL_TYPE STREQUAL Github)
        find_program(GIT_COMMAND NAMES git)

        if(GIT_COMMAND STREQUAL GIT_COMMAND-NOTFOUND)
            status(ERROR MESSAGE "Unable to find 'git'. Please install it to use Github dependencies")
        endif()

        if(EXISTS ${FETCH_DESTINATION})
            status(WARN MESSAGE "Removing directory at ${FETCH_DESTINATION}" PREFIX FETCH)
            file(REMOVE_RECURSE "${FETCH_DESTINATION}")
        endif()

        execute_process(
            COMMAND ${GIT_COMMAND} -c advice.detachedHead=false clone
            -q --separate-git-dir=${CMAKE_DEPENDENCY_STAGE}/.tmp
            --depth=1 --recurse-submodules --shallow-submodules --single-branch
            --branch ${FETCH_ID}
            ${FETCH_URL} ${FETCH_DESTINATION}
            OUTPUT_QUIET
            ERROR_VARIABLE GIT_ERROR
        )

        if(GIT_ERROR)
            status(ERROR MESSAGE "${GIT_ERROR}" PREFIX FETCH)
        endif()

        file(REMOVE_RECURSE ${CMAKE_DEPENDENCY_STAGE}/.git ${CMAKE_DEPENDENCY_STAGE}/.tmp)
    elseif(URL_TYPE STREQUAL Custom)
        status(ERROR MESSAGE "Custom URLs are currently not supported" PREFIX FETCH)
    else()
        status(ERROR MESSAGE "Unknown URL type for URL '${FETCH_URL}'" PREFIX FETCH)
    endif()

    return()
endfunction()

#############################################################
##################### Locking functions #####################
#############################################################

function(make_lockfile_hash)
    cmake_parse_arguments(PARSE_ARGV 1
        "LOCK"
        ""
        "URL;OUTPUT"
        ""
    )

    string(SHA512 ${LOCK_OUTPUT} "${LOCK_URL}")

    return(PROPAGATE ${LOCK_OUTPUT})
endfunction()

function(compare_lockfile_values DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "LOCK"
        "HASH;SYSTEM;OPTIONS;CONFIGURATION"
        "OUTPUT;"
        ""
    )

    if(LOCK_HASH)
        list(APPEND CHECKS HASH)
    endif()

    if(LOCK_SYSTEM)
        list(APPEND CHECKS SYSTEM)
    endif()

    if(LOCK_CONFIGURATION)
        list(APPEND CHECKS CONFIGURATION)
    endif()

    if(LOCK_OPTIONS)
        list(APPEND CHECKS OPTIONS)
    endif()

    if(LOCK_HASH)
        make_lockfile_hash(${DEPENDENCY} OUTPUT DEPENDENCY_HASH)
    endif()

    foreach(CHECK IN LISTS CHECKS)
        if(NOT ${DEPENDENCY}_${CHECK} AND NOT DEPENDENCY_${CHECK})
            continue()
        elseif(NOT ${DEPENDENCY}_${CHECK} STREQUAL DEPENDENCY_${CHECK})
            set(${LOCK_OUTPUT} ON)
            break()
        endif()
    endforeach()

    if(NOT DEFINED ${LOCK_OUTPUT})
        set(${LOCK_OUTPUT} OFF)
    endif()

    return(PROPAGATE ${LOCK_OUTPUT})
endfunction()

function(update_lockfile DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "LOCK"
        ""
        "URL;HASH;CONFIGURATION;SYSTEM"
        "OPTIONS;EXPORTS"
    )

    if(DEFINED LOCK_URL)
        make_lockfile_hash(URL ${LOCK_URL} OUTPUT LOCK_HASH)
    endif()

    if(NOT EXISTS ${CMAKE_LOCKFILE})
        file(TOUCH ${CMAKE_LOCKFILE})
        file(CHMOD ${CMAKE_LOCKFILE} PERMISSIONS
            OWNER_READ
            GROUP_READ
            WORLD_READ
        )

        if(DEFINED LOCK_HASH)
            file(APPEND ${CMAKE_LOCKFILE} "set(${DEPENDENCY}_HASH \"${LOCK_HASH}\")") 
        endif()

        if(DEFINED LOCK_SYSTEM)
            file(APPEND ${CMAKE_LOCKFILE} "set(${DEPENDENCY}_SYSTEM \"${LOCK_SYSTEM}\")")
        endif()

        if(DEFINED LOCK_CONFIGURATION)
            file(APPEND ${CMAKE_LOCKFILE} "set(${DEPENDENCY}_CONFIGURATION \"${LOCK_CONFIGURATION}\")")
        endif()

        if(DEFINED LOCK_OPTIONS)
            list(JOIN LOCK_OPTIONS " " OPTIONS)
            file(APPEND ${CMAKE_LOCKFILE} "set(${DEPENDENCY}_OPTIONS ${OPTIONS})")
        endif()

        if(DEFINED LOCK_EXPORTS)
            list(JOIN LOCK_EXPORTS " " EXPORTS)
            string(REPLACE "${CMAKE_DEPENDENCY_DESTINATION}/" "" EXPORTS "${EXPORTS}")
            file(APPEND ${CMAKE_LOCKFILE} "set(${DEPENDENCY}_EXPORTS ${EXPORTS})")
        endif()
    else()
        file(READ ${CMAKE_LOCKFILE} LOCKFILE)

        if(DEFINED LOCK_HASH)
            if(LOCKFILE MATCHES "set\\(${DEPENDENCY}_HASH .*\\)")
                string(REGEX REPLACE
                    "${DEPENDENCY}_HASH [^)]*" "${DEPENDENCY}_HASH \"${LOCK_HASH}\""
                    LOCKFILE "${LOCKFILE}"
                )
            else()
                set(LOCKFILE "${LOCKFILE}\nset(${DEPENDENCY}_HASH \"${LOCK_HASH}\")")
            endif()
        endif()

        if(DEFINED LOCK_SYSTEM)
            if(LOCKFILE MATCHES "set\\(${DEPENDENCY}_SYSTEM .*\\)")
                string(REGEX REPLACE
                    "${DEPENDENCY}_SYSTEM [^)]*" "${DEPENDENCY}_SYSTEM \"${LOCK_SYSTEM}\""
                    LOCKFILE "${LOCKFILE}"
                )
            else()
                set(LOCKFILE "${LOCKFILE}\nset(${DEPENDENCY}_SYSTEM \"${LOCK_SYSTEM}\")")
            endif()
        endif()

        if(DEFINED LOCK_CONFIGURATION)
            if(LOCKFILE MATCHES "set\\(${DEPENDENCY}_CONFIGURATION .*\\)")
                string(REGEX REPLACE
                    "${DEPENDENCY}_CONFIGURATION [^)]*"
                    "${DEPENDENCY}_CONFIGURATION \"${LOCK_CONFIGURATION}\""
                    LOCKFILE "${LOCKFILE}"
                )
            else()
                set(LOCKFILE "${LOCKFILE}\nset(${DEPENDENCY}_CONFIGURATION \"${LOCK_CONFIGURATION}\")")
            endif()
        endif()

        if(DEFINED LOCK_OPTIONS)
            list(JOIN LOCK_OPTIONS " " OPTIONS)
            if(LOCKFILE MATCHES "set\\(${DEPENDENCY}_OPTIONS .*\\)")
                string(REGEX REPLACE
                    "${DEPENDENCY}_OPTIONS [^)]*" "${DEPENDENCY}_OPTIONS ${OPTIONS}"
                    LOCKFILE "${LOCKFILE}"
                )
            else()
                set(LOCKFILE "${LOCKFILE}\nset(${DEPENDENCY}_OPTIONS ${OPTIONS})")
            endif()
        endif()

        if(DEFINED LOCK_EXPORTS)
            list(JOIN LOCK_EXPORTS " " EXPORTS)
            string(REPLACE "${CMAKE_DEPENDENCY_DESTINATION}/" "" EXPORTS "${EXPORTS}")
            if(LOCKFILE MATCHES "set\\(${DEPENDENCY}_EXPORTS .*\\)")
                string(REGEX REPLACE
                    "${DEPENDENCY}_EXPORTS [^)]*" "${DEPENDENCY}_EXPORTS ${EXPORTS}"
                    LOCKFILE "${LOCKFILE}"
                )
            else()
                string(REPLACE "${CMAKE_DEPENDENCY_DESTINATION}/" "" EXPORTS "${EXPORTS}")
                set(LOCKFILE "${LOCKFILE}\nset(${DEPENDENCY}_EXPORTS ${EXPORTS})")
            endif()
        endif()

        file(WRITE ${CMAKE_LOCKFILE} "${LOCKFILE}")
    endif()

    return()
endfunction()

function(reset_lockfile_variables DEPENDENCY)
    if(NOT EXISTS ${CMAKE_DEPENDENCY_MANIFEST}/${DEPENDENCY}.cmake)
        status(ERROR MESSAGE "Unknown dependency: ${DEPENDENCY}")
        message(FATAL_ERROR "")
    endif()

    set(${DEPENDENCY}_HASH "" PARENT_SCOPE)
    set(${DEPENDENCY}_OPTIONS "" PARENT_SCOPE)
    set(${DEPENDENCY}_SYSTEM "" PARENT_SCOPE)
    set(${DEPENDENCY}_CONFIGURATION "" PARENT_SCOPE)
    set(${DEPENDENCY}_EXPORTS "" PARENT_SCOPE)

    return()
endfunction()

#############################################################
############# Dependency manipulation functions #############
#############################################################

function(get_dependencies)
    cmake_parse_arguments(PARSE_ARGV 0
        "DEPENDENCY"
        ""
        "OUTPUT"
        ""
    )

    if(NOT DEFINED DEPENDENCY_OUTPUT)
        set(DEPENDENCY_OUTPUT DEPENDENCIES)
    endif()

    file(GLOB TMP "${CMAKE_DEPENDENCY_MANIFEST}/*.cmake")
    string(REGEX REPLACE "(${CMAKE_DEPENDENCY_MANIFEST}/|.cmake)" ""
        TMP "${TMP}"
    )

    macro(sort_dependencies DEPS)
        foreach(DEPENDENCY ${DEPS})
            if(DEPENDENCY IN_LIST GRAPH)
                continue()
            endif()

            unset(DEPENDS)

            include(${CMAKE_DEPENDENCY_MANIFEST}/${DEPENDENCY}.cmake)

            if(DEFINED DEPENDS)
                sort_dependencies(${DEPENDS})
            endif()

            list(APPEND GRAPH "${DEPENDENCY}")
            unset(DEPENDS)
        endforeach()
    endmacro()

    sort_dependencies("${TMP}")

    set(${DEPENDENCY_OUTPUT} "${GRAPH}" PARENT_SCOPE)

    return()
endfunction()

function(get_dependency_properties DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "DEPENDENCY"
        ""
        "PREFIX"
        "FROM"
    )

    if(NOT DEPENDENCY IN_LIST DEPENDENCY_FROM)
        status(ERROR MESSAGE "Unknown dependency: ${DEPENDENCY}")
        return()
    endif()

    if(NOT DEFINED DEPENDENCY_PREFIX)
        set(DEPENDENCY_PREFIX "DEPENDENCY")
    endif()

    unset(URL PARENT_SCOPE)
    unset(OPTIONS PARENT_SCOPE)
    unset(SYSTEM PARENT_SCOPE)
    unset(CONFIGURATION PARENT_SCOPE)
    unset(ENTRYPOINT PARENT_SCOPE)
    unset(COMMAND PARENT_SCOPE)
    unset(DISABLED PARENT_SCOPE)
    unset(CMAKE_USE_PRESET PARENT_SCOPE)
    unset(CMAKE_PRESET PARENT_SCOPE)
    unset(FILE PARENT_SCOPE)
    unset(VERSION PARENT_SCOPE)
    unset(COMPATIBILITY PARENT_SCOPE)

    include(${CMAKE_DEPENDENCY_MANIFEST}/${DEPENDENCY}.cmake)

    if(DISABLED)
        set(${DEPENDENCY_PREFIX}_DISABLED "${DISABLED}" PARENT_SCOPE)
        return()
    endif()

    if(NOT DEFINED SYSTEM)
        status(ERROR MESSAGE "Must define a build system for ${DEPENDENCY}. Set it via the SYSTEM variable")
    endif()

    if(NOT SYSTEM IN_LIST SUPPORTED_BUILD_SYSTEMS)
        list(JOIN SUPPORTED_BUILD_SYSTEMS " " SYSTEMS)
        status(ERROR MESSAGE "Unsupported build system: ${SYSTEM}. Expected one of ${SYSTEMS}")
    endif()

    if(NOT DEFINED CONFIGURATION)
        if(SYSTEM STREQUAL CMake)
            set(CONFIGURATION Release)
        elseif(SYSTEM STREQUAL Meson)
            set(CONFIGURATION release)
        endif()
    endif()

    if(SYSTEM STREQUAL CMake)
        if(NOT DEFINED COMMAND)
            set(COMMAND "${CMAKE_COMMAND}")
        endif()

        if(NOT DEFINED ENTRYPOINT)
            set(ENTRYPOINT ".")
        endif()

        if(CMAKE_USE_PRESET AND NOT DEFINED CMAKE_PRESET)
            set(CMAKE_PRESET default)
        endif()

        set(COMMAND_ARGUMENTS -B . -S )
    elseif(SYSTEM STREQUAL Meson)
        if(NOT DEFINED COMMAND)    
            find_program(MESON_COMMAND NAMES meson REQUIRED)
            set(COMMAND "${MESON_COMMAND}")
        endif()

        if(NOT DEFINED ENTRYPOINT)
            set(ENTRYPOINT ".")
        endif()
    elseif(SYSTEM STREQUAL Autoconf)
        set(CONFIGURATION None)

        if(NOT DEFINED COMMAND)
            find_program(MAKE_COMMAND NAMES make REQUIRED)
            set(COMMAND "${MAKE_COMMAND}")
        endif()

        if(NOT DEFINED ENTRYPOINT)
            set(ENTRYPOINT "..")
        endif() 
    endif()

    get_url_type(URL ${URL} OUTPUT URL_TYPE)

    if(URL_TYPE MATCHES Github)
        if(NOT DEFINED ID)
            status(ERROR MESSAGE "Dependency ${DEPENDENCY} does not specify a GitHub tag")
        endif()
    endif()

    if(DEFINED OPTIONS AND OPTIONS)
        foreach(OPTION "${OPTIONS}")
            if(OPTION MATCHES "([^=]+)=(.+)")
                set(NAME "${CMAKE_MATCH_1}")
                set(VALUE "${CMAKE_MATCH_2}")
            else()
                set(NAME "${OPTION}")
                set(VALUE "ON")
            endif()

            string(REPLACE ";" ":" VALUE "${VALUE}")

            if(NOT NAME IN_LIST NAMES)
                list(APPEND TMP "${NAME}=${VALUE}")
                list(APPEND NAMES "${NAME}")
            else()
                string(REGEX REPLACE "${NAME}=[^;]*(;)?" "${NAME}=${VALUE}\\1" TMP "${TMP}")
            endif()
        endforeach()
        
        list(SORT TMP)
        string(REPLACE "\"" "" OPTIONS "${OPTIONS}")
    endif()

    if(NOT DEFINED EXPORTS AND ${DEPENDENCY}_EXPORTS)
        set(EXPORTS "${${DEPENDENCY}_EXPORTS}")
    endif()

    if(NOT DEFINED LANGUAGES)
        set(LANGUAGES C CXX)
    endif()

    if(NOT SYSTEM STREQUAL CMake)
        if(NOT DEFINED VERSION)
            status(ERROR MESSAGE "Must specify a version for external dependencies" PREFIX DEPENDENCY)
        endif()

        if(NOT DEFINED COMPATIBILITY)
            set(COMPATIBILITY ExactVersion)
        endif()
    endif()

    set(${DEPENDENCY_PREFIX}_URL "${URL}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_ID "${ID}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_OPTIONS "${OPTIONS}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_SYSTEM "${SYSTEM}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_CONFIGURATION "${CONFIGURATION}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_ENTRYPOINT "${ENTRYPOINT}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_EXPORTS "${EXPORTS}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_COMMAND "${COMMAND}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_LANGUAGES "${LANGUAGES}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_FILE "${FILE}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_VERSION "${VERSION}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_COMPATIBILITY "${COMPATIBILITY}" PARENT_SCOPE)

    # CMake specific variables
    set(${DEPENDENCY_PREFIX}_CMAKE_USE_PRESET "${CMAKE_USE_PRESET}" PARENT_SCOPE)
    set(${DEPENDENCY_PREFIX}_CMAKE_PRESET "${CMAKE_PRESET}" PARENT_SCOPE)
endfunction()

function(fetch_dependency)
    cmake_parse_arguments(PARSE_ARGV 0
        "FETCH"
        ""
        "DESTINATION;SOURCE;URL;ID"
        ""
    )

    if(DEFINED FETCH_SOURCE)
        if(IS_DIRECTORY "${FETCH_SOURCE}")
            cmake_path(GET FETCH_DESTINATION PARENT_PATH FETCH_DESTINATION)
        endif()

        file(COPY "${FETCH_SOURCE}" DESTINATION "${FETCH_DESTINATION}")
    elseif(DEFINED FETCH_URL)
        fetch_url(
            URL "${FETCH_URL}"
            ID "${FETCH_ID}"
            DESTINATION "${FETCH_DESTINATION}"
        )
    endif()

    return()
endfunction()

function(configure_dependency DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "CONFIGURE"
        "IMPLICIT_VARIABLES"
        "SOURCE;DESTINATION"
        "FROM"
    )

    if(NOT CONFIGURE_IMPLICIT_VARIABLES)
        get_dependency_properties(${DEPENDENCY} FROM ${CONFIGURE_FROM} PREFIX DEPENDENCY)
    else()
        if(NOT DEPENDENCY IN_LIST CONFIGURE_FROM)
            status(ERROR MESSAGE "Unknown dependency ${DEPENDENCY}" PREFIX DEPENDENCY)
        endif()
    endif()

    if(NOT DEFINED CONFIGURE_SOURCE)
        set(CONFIGURE_SOURCE "${CMAKE_DEPENDENCY_SOURCE}/${DEPENDENCY}")
    endif()

    if(NOT DEFINED CONFIGURE_DESTINATION)
        set(CONFIGURE_DESTINATION "${CMAKE_DEPENDENCY_STAGE}/${DEPENDENCY}")
    endif()

    if(DEPENDENCY_SYSTEM STREQUAL CMake)
        foreach(OPTION IN LISTS DEPENDENCY_OPTIONS)
            if(OPTION MATCHES ";")
                string(REPLACE ";" "\;" OPTION "${OPTION}")
            endif()

            list(APPEND OPTIONS "-D${OPTION}")
        endforeach()

        set(CONFIGURE_COMMAND "${DEPENDENCY_COMMAND}")
        set(CONFIGURE_ARGUMENTS
            -Wno-dev --no-warn-unused-cli
            -DCMAKE_BUILD_TYPE=${DEPENDENCY_CONFIGURATION}
            -DCMAKE_INSTALL_PREFIX=${CMAKE_DEPENDENCY_DESTINATION}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            ${OPTIONS}
            -B ${CONFIGURE_DESTINATION}
        )

        if(DEPENDENCY_CMAKE_USE_PRESET)
            list(APPEND CONFIGURE_ARGUMENTS "--preset ${DEPENDENCY_CMAKE_PRESET}")
        else()
            list(APPEND CONFIGURE_ARGUMENTS "-S ${DEPENDENCY_ENTRYPOINT}")
        endif()
    elseif(DEPENDENCY_SYSTEM STREQUAL Meson)
        foreach(OPTION IN LISTS DEPENDENCY_OPTIONS)
            if(OPTION MATCHES ";")
                string(REPLACE ";" "\;" OPTION "${OPTION}")
            endif()

            list(APPEND OPTIONS "-D${OPTION}")
        endforeach()

        set(CONFIGURE_COMMAND "${DEPENDENCY_COMMAND}")
        set(CONFIGURE_ARGUMENTS
            setup --reconfigure ${CONFIGURE_DESTINATION} ${DEPENDENCY_ENTRYPOINT}
            --prefix=${CMAKE_DEPENDENCY_DESTINATION} --buildtype=${DEPENDENCY_CONFIGURATION}
            ${OPTIONS}
        )
    elseif(DEPENDENCY_SYSTEM STREQUAL Autoconf)
        file(MAKE_DIRECTORY "${CONFIGURE_DESTINATION}")

        set(CONFIGURE_COMMAND "${CONFIGURE_SOURCE}/${DEPENDENCY_ENTRYPOINT}/configure")
        set(CONFIGURE_ARGUMENTS
            --prefix=${CMAKE_DEPENDENCY_DESTINATION}
            ${DEPENDENCY_OPTIONS}
        )

        set(CONFIGURE_SOURCE "${CONFIGURE_DESTINATION}")
    endif()

    status(INFO MESSAGE "Configuring ${DEPENDENCY}")
    execute_process(
        WORKING_DIRECTORY ${CONFIGURE_SOURCE}
        COMMAND ${CONFIGURE_COMMAND} ${CONFIGURE_ARGUMENTS}
        OUTPUT_QUIET
        ERROR_VARIABLE CONFIGURE_ERROR
    )

    if(CONFIGURE_ERROR)
        if(EXISTS "${CONFIGURE_DESTINATION}")
            file(REMOVE_RECURSE "${CONFIGURE_DESTINATION}")
        endif()
        status(ERROR MESSAGE "${CONFIGURE_ERROR}" PREFIX CONFIGURE)
    endif()

    return()
endfunction()

function(build_dependency DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "BUILD"
        "ON_BUILD;IMPLICIT_VARIABLES"
        "SOURCE;DESTINATION"
        "FROM"
    )

    if(NOT BUILD_IMPLICIT_VARIABLES)
        get_dependency_properties(${DEPENDENCIES} FROM ${BUILD_FROM} PREFIX DEPENDENCY)
    else()
        if(NOT DEPENDENCY IN_LIST BUILD_FROM)
            status(ERROR MESSAGE "Unknown dependency ${DEPENDENCY}" PREFIX DEPENDENCY)
        endif()
    endif()

    if(NOT DEFINED BUILD_SOURCE)
        set(BUILD_SOURCE "${CMAKE_DEPENDENCY_STAGE}/${DEPENDENCY}")
    endif()

    if(NOT DEFINED BUILD_DESTINATION)
        set(BUILD_DESTINATION "${BUILD_SOURCE}")
    endif()

    if(DEPENDENCY_SYSTEM STREQUAL CMake)
        set(BUILD_COMMAND ${DEPENDENCY_COMMAND} --build .)
        set(BUILD_ARGUMENTS
            --config ${DEPENDENCY_CONFIGURATION}
            --parallel ${NPROC}
        )
    elseif(DEPENDENCY_SYSTEM STREQUAL Meson)
        set(BUILD_COMMAND ${DEPENDENCY_COMMAND} compile)
        set(BUILD_ARGUMENTS -j${NPROC})
    elseif(DEPENDENCY_SYSTEM STREQUAL Autoconf)
        set(BUILD_COMMAND ${DEPENDENCY_COMMAND})
        set(BUILD_ARGUMENTS -j${NPROC})
    endif()

    if(BUILD_ON_BUILD)
        status(INFO MESSAGE "Building ${DEPENDENCY}" OUTPUT BUILD_COMMENT)
        add_custom_command(
            OUTPUT ${BUILD_DESTINATION}/.build
            WORKING_DIRECTORY ${BUILD_SOURCE}
            VERBATIM COMMAND ${BUILD_COMMAND} ${BUILD_ARGUMENTS}
            USES_TERMINAL
            COMMENT "${BUILD_COMMENT}"
        )
    else()
        status(INFO MESSAGE "Building ${DEPENDENCY}")
        execute_process(
            WORKING_DIRECTORY ${BUILD_SOURCE}
            COMMAND ${BUILD_COMMAND} ${BUILD_ARGUMENTS}
            OUTPUT_QUIET
            ERROR_VARIABLE BUILD_ERROR
        )

        if(BUILD_ERROR)
            status(ERROR MESSAGE "${BUILD_ERROR}" PREFIX BUILD)
        endif()

        file(TOUCH ${BUILD_DESTINATION}/.build)
    endif()

    if(EXISTS ${BUILD_DESTINATION}/.build)    
        file(CHMOD ${BUILD_DESTINATION}/.build PERMISSIONS
            OWNER_READ
            GROUP_READ
            WORLD_READ
        )
    endif()

    return()
endfunction()

function(install_dependency DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "INSTALL"
        "ON_BUILD;IMPLICIT_VARIABLES"
        "SOURCE;DESTINATION"
        "FROM;WATCH"
    )

    if(NOT INSTALL_IMPLICIT_VARIABLES)
        get_dependency_properties(${DEPENDENCIES} FROM ${INSTALL_FROM} PREFIX DEPENDENCY)
    else()
        if(NOT DEPENDENCY IN_LIST INSTALL_FROM)
            status(ERROR MESSAGE "Unknown dependency ${DEPENDENCY}" PREFIX DEPENDENCY)
        endif()
    endif()

    if(NOT DEFINED INSTALL_SOURCE)
        set(INSTALL_SOURCE "${CMAKE_DEPENDENCY_STAGE}/${DEPENDENCY}")
    endif()

    if(NOT DEFINED INSTALL_DESTINATION)
        set(INSTALL_DESTINATION "${CMAKE_DEPENDENCY_DESTINATION}")
    endif()

    if(NOT DEFINED INSTALL_WATCH)
        set(INSTALL_WATCH "${INSTALL_SOURCE}/.install")
    endif()

    if(DEPENDENCY_SYSTEM STREQUAL CMake)
        set(INSTALL_COMMAND ${DEPENDENCY_COMMAND} --install .)
        set(INSTALL_ARGUMENTS
            --config ${DEPENDENCY_CONFIGURATION} --parallel ${NPROC}
        )
    elseif(DEPENDENCY_SYSTEM STREQUAL Meson)
        set(INSTALL_COMMAND ${DEPENDENCY_COMMAND} install)
        set(INSTALL_ARGUMENTS --no-rebuild --only-changed)
    elseif(DEPENDENCY_SYSTEM STREQUAL Autoconf)
        set(INSTALL_COMMAND ${DEPENDENCY_COMMAND} install)
        set(INSTALL_ARGUMENTS DESTDIR=${INSTALL_SOURCE}/.install)
    endif()

    foreach(WATCH IN LISTS INSTALL_WATCH)
        if(NOT IS_ABSOLUTE ${WATCH})
            string(PREPEND WATCH "${CMAKE_DEPENDENCY_DESTINATION}/")
        endif()
        list(APPEND NORMALIZED_WATCH "${WATCH}")
    endforeach()
    set(INSTALL_WATCH "${NORMALIZED_WATCH}")

    if(INSTALL_ON_BUILD)
        status(INFO MESSAGE "Installing ${DEPENDENCY}" OUTPUT INSTALL_COMMENT)
        add_custom_command(
            OUTPUT ${INSTALL_WATCH}
            WORKING_DIRECTORY ${INSTALL_SOURCE}
            VERBATIM COMMAND ${INSTALL_COMMAND} ${INSTALL_ARGUMENTS}
            USES_TERMINAL
            COMMENT "${INSTALL_COMMENT}"
            DEPENDS ${INSTALL_SOURCE}/.build
        )
    else()
        status(INFO MESSAGE "Installing ${DEPENDENCY}")
        execute_process(
            WORKING_DIRECTORY ${INSTALL_SOURCE}
            COMMAND ${INSTALL_COMMAND} ${INSTALL_ARGUMENTS}
            OUTPUT_QUIET
            ERROR_VARIABLE INSTALL_ERROR
        )

        if(INSTALL_ERROR)
            status(ERROR MESSAGE "${INSTALL_ERROR}" PREFIX INSTALL)
        endif()

        foreach(WATCH IN LISTS INSTALL_WATCH)
            if(NOT EXISTS ${WATCH})
                file(TOUCH "${WATCH}")
            endif()
        endforeach()
    endif()

    return()
endfunction()

function(retrieve_dependency_exports DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "RETRIEVE"
        "IMPLICIT_VARIABLES"
        "SOURCE;OUTPUT"
        "FROM"
    )

    if(NOT RETRIEVE_IMPLICIT_VARIABLES)
        get_dependency_properties(${DEPENDENCY} FROM ${RETRIEVE_FROM} PREFIX DEPENDENCY)
    else()
        if(NOT DEPENDENCY IN_LIST RETRIEVE_FROM)
            status(ERROR MESSAGE "Unknown dependency ${DEPENDENCY}" PREFIX DEPENDENCY)
        endif()
    endif()

    if(NOT DEFINED RETRIEVE_SOURCE)
        set(RETRIEVE_SOURCE "${CMAKE_DEPENDENCY_STAGE}/${DEPENDENCY}")
    endif()

    status(INFO MESSAGE "Retrieving exports of ${DEPENDENCY}")
    if(DEPENDENCY_SYSTEM STREQUAL CMake)
        file(STRINGS
            ${RETRIEVE_SOURCE}/install_manifest.txt
            ${RETRIEVE_OUTPUT}
        ) 
    elseif(DEPENDENCY_SYSTEM STREQUAL Meson)
        file(STRINGS
            ${RETRIEVE_SOURCE}/meson-logs/install-log.txt
            STRINGS
        )

        foreach(STRING IN LISTS STRINGS)
            if(STRING MATCHES "^#.*$")
                continue()
            endif()

            list(APPEND ${RETRIEVE_OUTPUT} "${STRING}")
        endforeach()
    elseif(DEPENDENCY_SYSTEM STREQUAL Autoconf)
        file(GLOB_RECURSE ${RETRIEVE_OUTPUT} "${RETRIEVE_SOURCE}/.install/*")
    endif() 

    string(REPLACE "${CMAKE_DEPENDENCY_DESTINATION}/" "" ${RETRIEVE_OUTPUT} "${${RETRIEVE_OUTPUT}}")

    return(PROPAGATE ${RETRIEVE_OUTPUT})
endfunction()

function(compute_dependency_hash DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "DEPENDENCY"
        ""
        "OUTPUT"
        ""
    )

    if(NOT EXISTS ${CMAKE_DEPENDENCY_MANIFEST}/${DEPENDENCY}.cmake)
        status(ERROR MESSAGE "Unknown dependency: ${DEPENDENCY}")
        return()
    else()
        include(${CMAKE_DEPENDENCY_MANIFEST}/${DEPENDENCY}.cmake)
    endif()

    if(URL MATCHES "https://github.com")
        if(NOT DEFINED ID)
            status(ERROR MESSAGE "Dependency ${DEPENDENCY} does not specify a GitHub tag")
            message(FATAL_ERROR "")
        endif()

        string(APPEND URL "/archive/refs/tags/${ID}")
    endif()

    string(SHA512 ${DEPENDENCY_OUTPUT} "${URL}")

    return(PROPAGATE ${DEPENDENCY_OUTPUT})
endfunction()

#############################################################
############# External system adapter functions #############
#############################################################

function(write_system_adapter DEPENDENCY)
    cmake_parse_arguments(PARSE_ARGV 1
        "ADAPTER"
        ""
        "VERSION;COMPATIBILITY"
        "LANGUAGES;EXPORTS"
    )

    include(CMakePackageConfigHelpers)

    execute_process(
        COMMAND ${CMAKE_COMMAND}
        --log-level=VERBOSE
        -DCMAKE_DEPENDENCIES_SYSTEM_ADAPTER=ON -P ${CMAKE_CURRENT_LIST_FILE}
        ERROR_VARIABLE ADAPTER
    )

    set(CMAKE_TARGET_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}")

    if(LINUX)
        set(CMAKE_HOST_TARGET "CMAKE_HOST_LINUX")
    elseif(APPLE)
        set(CMAKE_HOST_TARGET "CMAKE_HOST_APPLE")
    elseif(WIN32)
        set(CMAKE_HOST_TARGET "CMAKE_HOST_WIN32")
    elseif(BSD)
        set(CMAKE_HOST_TARGET "CMAKE_HOST_BSD")
    elseif(UNIX)
        set(CMAKE_HOST_TARGET "CMAKE_HOST_UNIX")
    endif()

    set(DEPENDENCY_LANGUAGES "${ADAPTER_LANGUAGES}")
    set(DEPENDENCY_EXPORTS "${ADAPTER_EXPORTS}")

    file(CONFIGURE
        OUTPUT ${CMAKE_DEPENDENCY_DESTINATION}/${CMAKE_INSTALL_LIBDIR}/cmake/${DEPENDENCY}Config.cmake
        CONTENT "${ADAPTER}"
        @ONLY
    )

    write_basic_package_version_file(
        ${CMAKE_DEPENDENCY_DESTINATION}/${CMAKE_INSTALL_LIBDIR}/cmake/${DEPENDENCY}ConfigVersion.cmake
        VERSION ${ADAPTER_VERSION}
        COMPATIBILITY ${ADAPTER_COMPATIBILITY}
    )

    return()
endfunction()

#############################################################
#############################################################
#############################################################

if(EXISTS ${CMAKE_LOCKFILE})
    include(${CMAKE_LOCKFILE})
endif()

get_dependencies(OUTPUT DEPENDENCIES)

foreach(DEPENDENCY IN LISTS DEPENDENCIES)
    set(CMAKE_CURRENT_DEPENDENCY_STAGE "${CMAKE_DEPENDENCY_STAGE}/${DEPENDENCY}")
    set(CMAKE_CURRENT_DEPENDENCY_SOURCE "${CMAKE_DEPENDENCY_SOURCE}/${DEPENDENCY}")

    get_dependency_properties(${DEPENDENCY} FROM ${DEPENDENCIES})

    if(DEPENDENCY_DISABLED)
        continue()
    endif()

    compare_lockfile_values(${DEPENDENCY} HASH OUTPUT SHOULD_UPDATE)

    if(SHOULD_UPDATE OR NOT EXISTS ${CMAKE_CURRENT_DEPENDENCY_SOURCE})
        reset_lockfile_variables(${DEPENDENCY})

        status(INFO MESSAGE "Fetching ${DEPENDENCY} at ${DEPENDENCY_URL}")
        if(DEFINED DEPENDENCY_FILE)
            fetch_dependency(
                SOURCE ${DEPENDENCY_FILE}
                DESTINATION ${CMAKE_CURRENT_DEPENDENCY_SOURCE}
            )
        elseif(DEFINED DEPENDENCY_URL)
            fetch_dependency(
                URL ${DEPENDENCY_URL}
                ID ${DEPENDENCY_ID}
                DESTINATION ${CMAKE_CURRENT_DEPENDENCY_SOURCE}
            )
        endif()

        update_lockfile(${DEPENDENCY} URL ${DEPENDENCY_URL})
    endif()

    status(INFO MESSAGE "Configuring ${DEPENDENCY}" OUTPUT CONFIGURE_COMMENT)
    status(INFO MESSAGE "Building ${DEPENDENCY}" OUTPUT BUILD_COMMENT)
    status(INFO MESSAGE "Installing ${DEPENDENCY}" OUTPUT INSTALL_COMMENT)

    compare_lockfile_values(${DEPENDENCY}
        SYSTEM CONFIGURATION OPTIONS
        OUTPUT SHOULD_UPDATE
    )

    if(SHOULD_UPDATE)
        if(EXISTS "${CMAKE_CURRENT_DEPENDENCY_STAGE}")
            file(REMOVE_RECURSE "${CMAKE_CURRENT_DEPENDENCY_STAGE}")
        endif()

        configure_dependency(${DEPENDENCY} FROM ${DEPENDENCIES}
            SOURCE ${CMAKE_CURRENT_DEPENDENCY_SOURCE}
            DESTINATION ${CMAKE_CURRENT_DEPENDENCY_STAGE}
            IMPLICIT_VARIABLES
        )

        if(CONFIGURE_ERROR)
            file(REMOVE_RECURSE "${CMAKE_CURRENT_DEPENDENCY_STAGE}")
            status(ERROR MESSAGE "${CONFIGURE_ERROR}" PREFIX CONFIGURE)
        endif()

        update_lockfile(${DEPENDENCY}
            SYSTEM ${DEPENDENCY_SYSTEM}
            CONFIGURATION ${DEPENDENCY_CONFIGURATION}
            OPTIONS ${DEPENDENCY_OPTIONS}
        )
    endif()

    if(NOT ${DEPENDENCY}_EXPORTS)
        build_dependency(${DEPENDENCY} FROM ${DEPENDENCIES}
            SOURCE ${CMAKE_CURRENT_DEPENDENCY_STAGE}
            IMPLICIT_VARIABLES
        )

        install_dependency(${DEPENDENCY} FROM ${DEPENDENCIES}
            SOURCE ${CMAKE_CURRENT_DEPENDENCY_STAGE}
            DESTINATION ${CMAKE_DEPENDENCY_DESTINATION}
            IMPLICIT_VARIABLES
        )

        retrieve_dependency_exports(${DEPENDENCY} FROM ${DEPENDENCIES}
            SOURCE ${CMAKE_CURRENT_DEPENDENCY_STAGE}
            OUTPUT ${DEPENDENCY}_EXPORTS
            IMPLICIT_VARIABLES
        )

        if(NOT DEPENDENCY_SYSTEM STREQUAL CMake)
            write_system_adapter(${DEPENDENCY}
                LANGUAGES ${DEPENDENCY_LANGUAGES}
                EXPORTS ${${DEPENDENCY}_EXPORTS}
                COMPATIBILITY ${DEPENDENCY_COMPATIBILITY}
                VERSION ${DEPENDENCY_VERSION}
            )

            list(APPEND ${DEPENDENCY}_EXPORTS
                ${CMAKE_INSTALL_LIBDIR}/cmake/${DEPENDENCY}Config.cmake
                ${CMAKE_INSTALL_LIBDIR}/cmake/${DEPENDENCY}ConfigVersion.cmake
            )
        endif()

        update_lockfile(${DEPENDENCY} EXPORTS ${${DEPENDENCY}_EXPORTS})
    endif()

    build_dependency(${DEPENDENCY} FROM ${DEPENDENCIES}
        SOURCE ${CMAKE_CURRENT_DEPENDENCY_STAGE}
        ON_BUILD IMPLICIT_VARIABLES
    )

    install_dependency(${DEPENDENCY} FROM ${DEPENDENCIES}
        SOURCE ${CMAKE_CURRENT_DEPENDENCY_STAGE}
        DESTINATION ${CMAKE_DEPENDENCY_DESTINATION}
        WATCH ${${DEPENDENCY}_EXPORTS}
        ON_BUILD IMPLICIT_VARIABLES
    )

    foreach(EXPORT IN LISTS ${DEPENDENCY}_EXPORTS)
        if(NOT IS_ABSOLUTE ${EXPORT})
            string(PREPEND EXPORT "${CMAKE_DEPENDENCY_DESTINATION}/")
        endif()
        list(APPEND EXPORTS "${EXPORT}")
    endforeach()
    set(${DEPENDENCY}_EXPORTS "${EXPORTS}")

    add_custom_target(${DEPENDENCY} ALL DEPENDS ${${DEPENDENCY}_EXPORTS})
endforeach()

endblock()
