set(CPACK_GENERATOR TGZ ZIP)

if(DEFINED PLATFORM)
    set(CPACK_PACKAGE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-${PLATFORM}")
else()
    set(CPACK_PACKAGE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}")
endif()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}")

include(CPack)
